version: '3.8'

services:
  db:
    image: postgres:15
    container_name: servatorum_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  api:
    build: .
    container_name: servatorum_api_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
